Added a script a generate a video mosaic with ffmpeg
+ reorganised 'generate_video' and added optical flow video generation

diff --git a/scripts/generate_videos b/scripts/generate_videos
--- a/scripts/generate_videos
+++ b/scripts/generate_videos
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 EXEC=$HOME/src/freeplay-sandbox-analysis/build/devel/lib/freeplay_sandbox_analysis/replay_with_poses
-DATASET_ROOT=/media/$USER/PInSoRo-backup/freeplay_sandbox/data
+DATASET_ROOT=/media/$USER/DoRoThy1/freeplay_sandbox/data
 
 orig_path=$(pwd)
 
@@ -22,44 +22,59 @@ do
         mkdir videos
     fi
 
-    # PURPLE CAMERA
+    # CAMERA + SKELETON
     if [ ! -f videos/camera_purple.mkv ]; then
         $EXEC --topic camera_purple/rgb/image_raw/compressed --path . --video videos/camera_purple.mkv || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
     fi
-    if [ ! -f videos/camera_purple_skel.mkv ]; then
-        $EXEC --topic camera_purple/rgb/image_raw/compressed --path . --video videos/camera_purple_skel.mkv --camera=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
-
-    fi
-    if [ ! -f videos/camera_purple_raw.mkv ]; then
-        $EXEC --topic camera_purple/rgb/image_raw/compressed --path . --video videos/camera_purple_raw.mkv --skeleton=0 --face=0 --hand=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
-
-    fi
-
-    # YELLOW CAMERA
     if [ ! -f videos/camera_yellow.mkv ]; then
         $EXEC --topic camera_yellow/rgb/image_raw/compressed --path . --video videos/camera_yellow.mkv || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
 
     fi
-    if [ ! -f videos/camera_yellow_skel.mkv ]; then
-        $EXEC --topic camera_yellow/rgb/image_raw/compressed --path . --video videos/camera_yellow_skel.mkv --camera=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+    if [ ! -f videos/env_camera.mkv ]; then
+        $EXEC --topic env_camera/qhd/image_color/compressed --path . --video videos/env_camera.mkv || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+
+    fi
+
+    # CAMERA ALONE
+    if [ ! -f videos/camera_purple_raw.mkv ]; then
+        $EXEC --topic camera_purple/rgb/image_raw/compressed --path . --video videos/camera_purple_raw.mkv --skeleton=0 --face=0 --hand=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
 
     fi
     if [ ! -f videos/camera_yellow_raw.mkv ]; then
         $EXEC --topic camera_yellow/rgb/image_raw/compressed --path . --video videos/camera_yellow_raw.mkv --skeleton=0 --face=0 --hand=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
 
     fi
+    if [ ! -f videos/env_camera_raw.mkv ]; then
+        $EXEC --topic env_camera/qhd/image_color/compressed --path . --video videos/env_camera_raw.mkv --skeleton=0 --face=0 --hand=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+
+    fi
+
+    # OPTICAL FLOW -- Attention! Extremely slow!
+    if [ ! -f videos/camera_purple_optical_flow.mkv ]; then
+        $EXEC --topic camera_purple/rgb/image_raw/compressed --path . --opticalflow=on --video videos/camera_purple_optical_flow.mkv || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+
+    fi
+    if [ ! -f videos/camera_yellow_optical_flow.mkv ]; then
+        $EXEC --topic camera_yellow/rgb/image_raw/compressed --path . --opticalflow=on --video videos/camera_yellow_optical_flow.mkv || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+
+    fi
+    if [ ! -f videos/env_camera_optical_flow.mkv ]; then
+        $EXEC --topic env_camera/qhd/image_color/compressed --path . --opticalflow=on --video videos/env_camera_optical_flow.mkv || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+
+    #fi
+
     
-    # ENV CAMERA
-    if [ ! -f videos/env_camera.mkv ]; then
-        $EXEC --topic env_camera/qhd/image_color/compressed --path . --video videos/env_camera.mkv || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+    # SKELETON ALONE
+    if [ ! -f videos/camera_purple_skel.mkv ]; then
+        $EXEC --topic camera_purple/rgb/image_raw/compressed --path . --video videos/camera_purple_skel.mkv --camera=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
+
+    fi
+    if [ ! -f videos/camera_yellow_skel.mkv ]; then
+        $EXEC --topic camera_yellow/rgb/image_raw/compressed --path . --video videos/camera_yellow_skel.mkv --camera=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
 
     fi
     if [ ! -f videos/env_camera_skel.mkv ]; then
         $EXEC --topic env_camera/qhd/image_color/compressed --path . --video videos/env_camera_skel.mkv --camera=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
-
-    fi
-    if [ ! -f videos/env_camera_raw.mkv ]; then
-        $EXEC --topic env_camera/qhd/image_color/compressed --path . --video videos/env_camera_raw.mkv --skeleton=0 --face=0 --hand=0 || { echo "video creation failed for $dir. Skipping." ; cd ..; continue; }
 
     fi
 
